apiVersion: v1
kind: ServiceAccount
metadata:
  name:  akka-cluster-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akka-cluster-role
rules:
# We need to be able to iterate the members of a pod when using the kubernetes-api discovery mechanism
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: akka-cluster-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: akka-cluster-role
subjects:
  - kind: ServiceAccount
    name:  akka-cluster-sa
